#-------------------------------------------
# Main configuration of ozserver/ozservlet
#-------------------------------------------

path.oz.server.home=%OZ_RUNNING_PATH%/WEB-INF
# path.oz.server.home=C:/dev/kids/back-end/ca-be/src/resources/webapp/WEB-INF

path.license.file=%OZ_HOME%/license/ozlicense.xml
path.xml.properties.file=%OZ_HOME%/conf/xml.properties
path.log.properties.file=%OZ_HOME%/conf/log.properties
path.securitypolicy.properties.file=%OZ_HOME%/conf/spmgr.properties
path.connpool.properties.file=%OZ_HOME%/conf/db.properties
path.cache.properties.file=%OZ_HOME%/conf/cachemngr.properties
path.monitor.properties.file=%OZ_HOME%/conf/monitor.properties
path.repository.properties.file=%OZ_HOME%/conf/repository.properties
path.usl.properties.file=%OZ_HOME%/conf/uslmngr.properties
path.ozudr.properties.file=%OZ_HOME%/conf/ozudr.properties
path.schedule.properties.file=%OZ_HOME%/conf/srmngr.properties
path.sapclient.properties.file=%OZ_HOME%/conf/sap.properties
path.databind.properties.file=%OZ_HOME%/conf/databind.properties
path.ozservice.properties.file=%OZ_HOME%/conf/ozservice.properties
path.ozdbconfig.properties.file=%OZ_HOME%/conf/dbconfig.xml
path.ozudl.properties.file=%OZ_HOME%/conf/ozudl.properties
path.datasource.properties.file=%OZ_HOME%/conf/datasource.properties
path.mail.properties.file=%OZ_HOME%/conf/mail.properties
path.html5manager.properties.file=%OZ_HOME%/conf/html5manager.properties
path.html5managerhealthcheck.properties.file=%OZ_HOME%/conf/html5managerhealthcheck.properties
path.schedulerlist.properties.file=%OZ_HOME%/conf/schedulermanager.properties
path.viewerparameter.properties.file=%OZ_HOME%/conf/viewer_parameter_en_us.xml
path.webconsole.properties.file=%OZ_HOME%/conf/ozwebconsole.properties
path.nosql.properties.file=%OZ_HOME%/conf/nosql.properties
path.ozqrcode.properties.file=%OZ_HOME%/conf/ozqrcode.properties
